<!DOCTYPE html>
<html>
    <head>
        <title>Destinations</title>
        <link rel="stylesheet" href="destinations.css">
        
        
    </head>
    <body>
        <div id='container'>
            <div id='header'>
                <h1>&nbspLaflef</h1>
            </div>
            <div id='pages'>
                <br>
                <a href="projecthtml.php" target="_self">Home</a>
                <a href="aboutus.php"target="_self">About us</a>
                <a href="tours.php" target="_self">Tours</a>
                <a href="signup2.PHP">Sign up</a>
                <a href="login.PHP" target="_self">Log in</a>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            
           <div id="divat">
            
                <div class="aadivs" id='deadsea' onclick='ds2()'><h2>DEAD SEA</h2></div>
                <div class="aadivs" id="ajloun" onclick="aj()"><h2>AJLOUN</h2></div>
                <div class="aadivs" id="abdali" onclick="ab()"><h2>ABDALI</h2></div>
                <div class="aadivs" id="jarash" onclick="jar()"><h2>JERASH</h2></div>
                
                <div class="aadivs" id="wadirum" onclick="wr()"><h2>WADI RUM </h2></div>
                <div class="aadivs" id="petra" onclick="pt()"><h2>PETRA</h2></div>
                <div class="aadivs" id="aqaba" onclick="aq()"><h2>AQABA</h2></div>
                <div class="aadivs" id="mountnebo" onclick="mo()"><h2>MOUNT NEBO</h2></div>
            
                <div id="thirdthree">
                <div class="aadivs" id="rt" onclick="ro()"><h2>ROMAN<br>THEATER</h2></div>
                <div class="aadivs" id="maghtas" onclick="mg()"><h2>AL MAGHTAS</h2></div>
                <div class="aadivs" id="uq" onclick="uq()"><h2>UM QAIS</h2></div>
                <div class="aadivs" id="springs" onclick="ms()"><h2>MA'IN<br>SPRINGS</h2></div>
           
           </div>
        </div>

        <script>
        function ds2(){
            window.open("deadsea.html");
        }
        
        function aj(){
            window.open("ajloun.html");
        }
        
        function ab(){
            window.open("abdali.html");
        }
        
        function jar(){
            window.open("jarash.html");
        }
        
        function wr(){
            window.open("wadirum.html");
        }
        
        function pt(){
            window.open("petra.html");
        }
        
        function aq(){
            window.open("aqaba.html");
        }
        
        function mo(){
            window.open("mountnebo.html");
        }
        
        
        function ro(){
            window.open("romantheater.html");
        }
        
        function mg(){
            window.open("almaghtas.html");
        }
        
        function uq(){
            window.open("umqais.html");
        }
        
        function ms(){
            window.open("mainsprings.html");
        }
        
        </script>
    </body>
</html>