<?php include('server.php') ?>
<!DOCTYPE html>
<html>
<head>
<title>Hello</title>
<link rel="stylesheet" href="hello.css">
</head>

<body>
<h1>HELLO</h1>

<div>
<h2>welcome to our Family :) </h2>
<h2>We are Extremly glad to have you here </h2>
<h2>Are You Ready to Explore The Beautiful Sights of Jordan </h2>
<h2>Please be Aware that you have to login inorder to book your fun trip</h2>
<h2>To login please <a href="login.PHP">CLICK HERE </a></h2>
</div>
</body>


</html>