<?php include('newsletterserver.php') ?>
<!DOCTYPE html>
<html>
<head>
<title>Hello</title>
<link rel="stylesheet" href="subscribe.css">
</head>

<body>
<h1>Newsletter</h1>

<div>
<h2>Welcome :) </h2>
<h2>You Successfully Subscribed To Our Newsletter</h2>
<h2>Stay Tuned To Our Daily Offers and New Adventures</h2>
<h2><a href="projecthtml.php">CLICK ME </a>To Go Back To Our Home Page </h2>
</div>
</body>


</html>